#!/usr/bin/perl
use strict;

open FILE,"$ARGV[0]";

while(<FILE>){
	chomp;
	my @aa = split;
        my $all_reads_number = 16510408;
        my $relative_depth = $aa[1]/$all_reads_number*1000000;
print "$aa[0]\t$aa[1]\t$all_reads_number\t$relative_depth\n";
}
close FILE;
